---
apiVersion: v1
kind: Pod
metadata:
  name: tresata-dune-web-api
  namespace: dune
  labels:
    app: tresata-dune-web-api
spec:
  containers:
    - name: tresata-dune-web-api
      image: 513423204767.dkr.ecr.us-east-1.amazonaws.com/tresata/dune-api:0.1.0-SNAPSHOT
      imagePullPolicy: Always
      ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: tresata-dune-web-api
  name: tresata-dune-web-api
  namespace: dune
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tresata-dune-web-api
